### ISSUE TITLE
Proposed API revisions

### ISSUE THREAD

**Issue by kstaken** [terascope/teraslice_op_test_harness#2]
After playing with this I'd like to suggest a revised API. The current API kind of assumes the developer understands the calling sequence within teralice. That shouldn't be necessary in order to write tests.

```javascript
var harness = require('teraslice_op_test_harness')();

var testdata = whatever;

describe('The my_op processor', function() {
    it('Should run some test', function() {
        // default opConfig
        expect(harness.run('my_op', testdata).length).toBe(1);

       // custom opConfig
        var opConfig = harness.opConfig(); 
        opConfig.size = 100;
        expect(harness.run('my_op', testdata, opConfig).length).toBe(1);

       // scratch opConfig
       var opConfig = {
            size: 100
       }
       expect(harness.run('my_op', testdata, opConfig).length).toBe(1);
    });
});
```

`harness.opConfig()` would return a new instance of an opConfig initialized with the schema using convict. Each call would return a fresh object so there's no need for the user to worry about cloning or anything. It's important that the defaults get applied since that's how it will show up in Teraslice.

`harness.run(opName, testData, opConfig)` where opConfig is optional. opName is the name of the operation and the harness will load the module trying a few different mechanisms. First looking for the module as a regular module, then looking for a directory with the name of the module at the same level as the spec directory and then finally just falling back to index.js. If opConfig is missing then a new instance should be created with defaults and if opConfig is provided then it should be validated using convict to make sure it has all the defaults. This convict stuff may be somewhat tricky but this isn't really going to work without it.
     * Also for the file loading we may need an independent setting that hints the harness on where to find the module but hopefully most cases can be handled with defaults.

Ideally the harness should hide the details of the context and loggers and such. They should just appear as they do in Teraslice where the processor developer has no control over them. 

The context in particular will need to mock the APIs that teraslice exposes through it. This means things like getting connections and the API to get an assets path.  Everything that Teraslice exposes to a processor is going to have to be mocked here which should really help with formalizing the interface between Teraslice and ops.

**Comment by kstaken** [comment]
Thinking about this more `harness.opConfig()` may not even be necessary (also realized it won't work anyway as it doesn't know the name of the op). If `harness.run()` is handling validation then simply giving it config as you would in a job is likely all that's required.

**Comment by kstaken** [comment]
More thinking, I'm not sure why I was thinking the `opName` needs to be passed to the run function. Passing it at the point when the harness is loaded would be better.

```
var harness = require('teraslice_op_test_harness')('my_op');

var testdata = whatever;

describe('The my_op processor', function() {
    it('Should run some test', function() {
        // default opConfig
        expect(harness.run(testdata).length).toBe(1);

       // scratch opConfig
       var opConfig = {
            size: 100
       }
       expect(harness.run(testdata, opConfig).length).toBe(1);
    });
});
```

**Comment by godber** [comment]
This is done.
